only use pacman if it exists

diff --git a/install b/install
--- a/install
+++ b/install
@@ -3,7 +3,11 @@ set -e
 
 echo "Install arch pacman deps"
 i(){
-	sudo pacman -S --needed $1
+	if ! [ -x "$(command -v pacman)" ]; then
+	  echo "pacman not found. skipping install of $@"
+	  return
+	fi
+	sudo pacman -S --needed $@
 }
 i neovim python-pynvim
 i noto-fonts-cjk noto-fonts-emoji noto-fonts-extra ttf-bitstream-vera ttf-croscore ttf-dejavu ttf-hack ttf-roboto ttf-hack #fonts
